apiVersion: v1
kind: Namespace
metadata:
  name: project-wta
---
apiVersion: v1
kind: Service
metadata:
  name: project-wta-gtw-svc
  namespace: project-wta
spec:
  selector:
    app: project-wta
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: project-wta
    protocol: TCP
    port: 80
    targetPort: 80
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  project-wta-gtw-api-dep
  namespace: project-wta
  labels:
    app:  project-wta
spec:
  selector:
    matchLabels:
      app: project-wta
  template:
    metadata:
      labels:
        app:  project-wta
    spec:
      containers:
      - name:  project-wta-gtw-api
        image:  weslenalmeida/project-getway:dev
        ports:
          - containerPort: 80
        env:
          - name: ApiKey
            value: "3a20b0d9-d576-4300-b5be-f4f23664feee"
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
          limits:
            cpu: 300m
            memory: 300Mi
        volumeMounts:
        - name: ocelot-volume
          mountPath: app/ocelot.json
          subPath: ocelot.json
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10    
        terminationMessagePath: /local/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      volumes:
      - name: ocelot-volume
        configMap:
          name: internal-api-gateway-config  
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%    
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: project-wta-gtw-hpa
  namespace: project-wta
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-wta
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-api-gateway-config
  namespace: project-wta
  labels:
    app:  project-wta
data:
  ocelot.json: |-
    {
      "Routes": [
        {
          "DownstreamPathTemplate": "/api/v1/token",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "project-wta-aut-api-svc",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/api/token",
          "UpstreamHttpMethod": [ "Post", "Get" ],
          "RateLimitOptions": {
            "EnableRateLimiting": true,
            "Period": "1s",
            "PeriodTimespan": 10,
            "Limit": 1
          }
        }
      ],
      "GlobalConfiguration": {
        "ServiceDiscoveryProvider": {
          "Host": "192.168.49.2",
          "Port": 443,
          "Namespace": "project-wta",
          "Type": "pollkube",
          "PollingInterval": 100
        },
        "RateLimitOptions": {
          "DisableRateLimitHeaders": false,
          "QuotaExceededMessage": "Rate limit !",
          "HttpStatusCode": 429
        }
      },
      "DelegatingHandlers": [
        "ApiKeyHandler"
      ]
    }        



 
 

    

    
    
      